config/routes.rb
Rails.application.routes.draw do
  resources :leaders do
    resources :contact_informations
    resources :emergency_contacts
    resources :demographics
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "leaders#index"
end

app/models/leader.rb
class Leader < ApplicationRecord
end

app/controllers/leaders_controller.rb
class LeadersController < ApplicationController
  before_action :set_leader, only: %i[ show edit update destroy ]

  # GET /leaders or /leaders.json
  def index
    @leaders = Leader.all
  end

  # GET /leaders/1 or /leaders/1.json
  def show
  end

  # GET /leaders/new
  def new
    @leader = Leader.new
  end

  # GET /leaders/1/edit
  def edit
  end

  # POST /leaders or /leaders.json
  def create
    @leader = Leader.new(leader_params)

    respond_to do |format|
      if @leader.save
        format.html { redirect_to @leader, notice: "Leader was successfully created." }
        format.json { render :show, status: :created, location: @leader }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @leader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leaders/1 or /leaders/1.json
  def update
    respond_to do |format|
      if @leader.update(leader_params)
        format.html { redirect_to @leader, notice: "Leader was successfully updated." }
        format.json { render :show, status: :ok, location: @leader }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @leader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaders/1 or /leaders/1.json
  def destroy
    @leader.destroy!

    respond_to do |format|
      format.html { redirect_to leaders_path, status: :see_other, notice: "Leader was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leader
      @leader = Leader.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def leader_params
      params.expect(leader: [ :first_name, :middle_name, :last_name, :suffix, :preferred_name, :other_names, :pronouns, :self_identified_gender ])
    end
end

app/helpers/leaders_helper.rb
module LeadersHelper
end

app/views/leaders/_form.html.erb
<%= form_with(model: leader) do |form| %>
  <% if leader.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(leader.errors.count, "error") %> prohibited this leader from being saved:</h2>

      <ul>
        <% leader.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :middle_name, style: "display: block" %>
    <%= form.text_field :middle_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :suffix, style: "display: block" %>
    <%= form.text_field :suffix %>
  </div>

  <div>
    <%= form.label :preferred_name, style: "display: block" %>
    <%= form.text_field :preferred_name %>
  </div>

  <div>
    <%= form.label :other_names, style: "display: block" %>
    <%= form.text_field :other_names %>
  </div>

  <div>
    <%= form.label :pronouns, style: "display: block" %>
    <%= form.text_field :pronouns %>
  </div>

  <div>
    <%= form.label :self_identified_gender, style: "display: block" %>
    <%= form.text_field :self_identified_gender %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/leaders/_leader.html.erb
<div id="<%= dom_id leader %>">
  <p>
    <strong>First name:</strong>
    <%= leader.first_name %>
  </p>

  <p>
    <strong>Middle name:</strong>
    <%= leader.middle_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= leader.last_name %>
  </p>

  <p>
    <strong>Suffix:</strong>
    <%= leader.suffix %>
  </p>

  <p>
    <strong>Preferred name:</strong>
    <%= leader.preferred_name %>
  </p>

  <p>
    <strong>Other names:</strong>
    <%= leader.other_names %>
  </p>

  <p>
    <strong>Pronouns:</strong>
    <%= leader.pronouns %>
  </p>

  <p>
    <strong>Self identified gender:</strong>
    <%= leader.self_identified_gender %>
  </p>

</div>

app/views/leaders/edit.html.erb
<% content_for :title, "Editing leader" %>

<h1>Editing leader</h1>

<%= render "form", leader: @leader %>

<br>

<div>
  <%= link_to "Show this leader", @leader %> |
  <%= link_to "Back to leaders", leaders_path %>
</div>

app/views/leaders/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Leaders" %>

<h1>Leaders</h1>
<div id="leaders" class="container">
  <% @leaders.each do |leader| %>
    <%= render leader %>
    <p>
      <%= link_to "Show this leader", leader %>
    </p>
  <% end %>
</div>

<%= link_to "New leader", new_leader_path %>

app/views/leaders/new.html.erb
<% content_for :title, "New leader" %>

<h1>New leader</h1>

<%= render "form", leader: @leader %>

<br>

<div>
  <%= link_to "Back to leaders", leaders_path %>
</div>

app/views/leaders/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="columns">
  <div class="column">
    <%= render "application/sidebar", leader:@leader %>
  </div>
  <div class="column is-three-quarters">
    <%= render @leader %>
  </div>
</div>
<div>
  <%= link_to "Edit this leader", edit_leader_path(@leader) %> |
  <%= link_to "Back to leaders", leaders_path %>
  <%= button_to "Destroy this leader", @leader, method: :delete %>
</div>