config/routes.rb
Rails.application.routes.draw do
  resources :leaders do
    resources :contact_informations
    resources :emergency_contacts
    resources :demographics
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "leaders#index"
end

app/models/emergency_contact.rb
class EmergencyContact < ApplicationRecord
  belongs_to :leader
end

app/controllers/emergency_contacts_controller.rb
class EmergencyContactsController < ApplicationController
  before_action :set_emergency_contact, only: %i[ show edit update destroy ]
  before_action :set_leader
  def index
    @emergency_contact = EmergencyContact.where(leader_id: params[:leader_id]).first_or_create
  end

  # GET /emergency_contacts/1 or /emergency_contacts/1.json
  def show
    @emergency_contact = EmergencyContact.where(leader_id: params[:leader_id]).first_or_create
  end

  # GET /emergency_contacts/new
  def new
    @emergency_contact = EmergencyContact.new
  end

  # GET /emergency_contacts/1/edit
  def edit
  end

  # POST /emergency_contacts or /emergency_contacts.json
  def create
    @emergency_contact = EmergencyContact.new(emergency_contact_params)

    respond_to do |format|
      if @emergency_contact.save
        format.html { redirect_to @emergency_contact, notice: "Contact information was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emergency_contacts/1 or /emergency_contacts/1.json
  def update
    respond_to do |format|
      if @emergency_contact.update(emergency_contact_params)
        format.html { redirect_to leader_emergency_contacts_path(@leader), notice: "Contact information was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emergency_contacts/1 or /emergency_contacts/1.json
  def destroy
    @emergency_contact.destroy!

    respond_to do |format|
      format.html { redirect_to leaders_emergency_contacts_path, status: :see_other, notice: "Contact information was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emergency_contact
      @emergency_contact = EmergencyContact.find_by leader_id: params[:leader_id].first
      if @emergency_contact.nil?
        @emergency_contact = EmergencyContact.new(leader_id: params[:leader_id].first)
      end
      return @emergency_contact
    end

    def set_leader
      @leader = Leader.find(params[:leader_id])
    end

    # Only allow a list of trusted parameters through.
    def emergency_contact_params
      params.expect(emergency_contact: [ :leader_id, :firstName, :middleName, :lastName, :phoneNumber, :streetAddress1, :streetAddress2, :city, :state, :zip, :country, :email ])
    end
end

app/helpers/emergency_contacts_helper.rb
module EmergencyContactsHelper
end

app/views/emergency_contacts/_emergency_contact.html.erb
<div id="<%= dom_id emergency_contact %>">
  <p>
    <strong>Firstname:</strong>
    <%= emergency_contact.firstName %>
  </p>
  <p>
    <strong>Middlename:</strong>
    <%= emergency_contact.middleName %>
  </p>
  <p>
    <strong>Lastname:</strong>
    <%= emergency_contact.lastName %>
  </p>
  <p>
    <strong>Phonenumber:</strong>
    <%= emergency_contact.phoneNumber %>
  </p>
  <p>
    <strong>Streetaddress1:</strong>
    <%= emergency_contact.streetAddress1 %>
  </p>
  <p>
    <strong>Streetaddress2:</strong>
    <%= emergency_contact.streetAddress2 %>
  </p>
  <p>
    <strong>City:</strong>
    <%= emergency_contact.city %>
  </p>
  <p>
    <strong>State:</strong>
    <%= emergency_contact.state %>
  </p>
  <p>
    <strong>Zip:</strong>
    <%= emergency_contact.zip %>
  </p>
  <p>
    <strong>Country:</strong>
    <%= emergency_contact.country %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= emergency_contact.email %>
  </p>
  <%= link_to "Edit this emergency contact", edit_leader_emergency_contact_path(@leader, emergency_contact) %>
</div>

app/views/emergency_contacts/_form.html.erb
<%= form_with(model: [@leader, emergency_contact]) do |form| %>
  <% if emergency_contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(emergency_contact.errors.count, "error") %> prohibited this emergency_contact from being saved:</h2>
      <ul>
        <% emergency_contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :leader_id, style: "display: block" %>
    <%= form.text_field :leader_id %>
  </div>
  <div>
    <%= form.label :firstName, style: "display: block" %>
    <%= form.text_field :firstName %>
  </div>
  <div>
    <%= form.label :middleName, style: "display: block" %>
    <%= form.text_field :middleName %>
  </div>
  <div>
    <%= form.label :lastName, style: "display: block" %>
    <%= form.text_field :lastName %>
  </div>
  <div>
    <%= form.label :phoneNumber, style: "display: block" %>
    <%= form.text_field :phoneNumber %>
  </div>
  <div>
    <%= form.label :streetAddress1, style: "display: block" %>
    <%= form.text_field :streetAddress1 %>
  </div>
  <div>
    <%= form.label :streetAddress2, style: "display: block" %>
    <%= form.text_field :streetAddress2 %>
  </div>
  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>
  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>
  <div>
    <%= form.label :zip, style: "display: block" %>
    <%= form.text_field :zip %>
  </div>
  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/emergency_contacts/edit.html.erb
<% content_for :title, "Editing emergency contact" %>
<h1>Editing emergency contact</h1>
<%= render "form", emergency_contact: @emergency_contact %>
<br>
<div>
  <%= link_to "Back to emergency contacts", leader_emergency_contacts_path %>
</div>

app/views/emergency_contacts/index.html.erb
<p style="color: green"><%= notice %></p>
<% content_for :title, "Emergency contact" %>
<h1>Emergency contact</h1>
<div class="columns">
  <div class="column">
    <%= render "application/sidebar", leader:@leader %>
  </div>
  <div class="column is-three-quarters">
    <%= render @emergency_contact %>
  </div>
</div>