config/routes.rb
Rails.application.routes.draw do
  resources :leaders do
    resources :contact_informations
    resources :emergency_contacts
    resources :demographics
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "leaders#index"
end

app/models/demographic.rb
class Demographic < ApplicationRecord
  belongs_to :leader
end

app/controllers/demographics_controller.rb
class DemographicsController < ApplicationController
  before_action :set_demographic, only: %i[ show edit update destroy ]

before_action :set_leader
  def index
    @demographic = Demographic.where(leader_id: params[:leader_id]).first_or_create
  end

  # GET /demographics/1 or /demographics/1.json
  def show
    @demographic = Demographic.where(leader_id: params[:leader_id]).first_or_create
  end

  # GET /demographics/new
  def new
    @demographic = Demographic.new
  end

  # GET /demographics/1/edit
  def edit
  end

  # POST /demographics or /demographics.json
  def create
    @demographic = Demographic.new(demographic_params)

    respond_to do |format|
      if @demographic.save
        format.html { redirect_to @demographic, notice: "Contact information was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demographics/1 or /demographics/1.json
  def update
    respond_to do |format|
      if @demographic.update(demographic_params)
        format.html { redirect_to leader_demographics_path(@leader), notice: "Contact information was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demographics/1 or /demographics/1.json
  def destroy
    @demographic.destroy!

    respond_to do |format|
      format.html { redirect_to leaders_demographics_path, status: :see_other, notice: "Contact information was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demographic
      @demographic = Demographic.find_by leader_id: params[:leader_id].first
      if @demographic.nil?
        @demographic = Demographic.new(leader_id: params[:leader_id].first)
      end
      return @demographic
    end

    def set_leader
      @leader = Leader.find(params[:leader_id])
    end

    # Only allow a list of trusted parameters through.
    def demographic_params
      params.expect(demographic: [ :leader_id, :raceAmericanIndian, :raceAsian, :raceBlack, :raceHispanic, :raceHawaiian, :raceWhite, :raceDidNotProvide, :gender, :dateOfBirth, :cityOfBirth, :stateOfBirth, :language, :military, :parent1EducationalLevel, :parent2EducationalLevel, :currentHouseholdIncome ])
    end
end

app/helpers/demographics_helper.rb
module DemographicsHelper
end

app/views/demographics/_demographic.html.erb
<div id="<%= dom_id demographic %>">
  <p>
    <strong>Leader:</strong>
    <%= demographic.leader_id %>
  </p>
  <p>
    <strong>Raceamericanindian:</strong>
    <%= demographic.raceAmericanIndian %>
  </p>
  <p>
    <strong>Raceasian:</strong>
    <%= demographic.raceAsian %>
  </p>
  <p>
    <strong>Raceblack:</strong>
    <%= demographic.raceBlack %>
  </p>
  <p>
    <strong>Racehispanic:</strong>
    <%= demographic.raceHispanic %>
  </p>
  <p>
    <strong>Racehawaiian:</strong>
    <%= demographic.raceHawaiian %>
  </p>
  <p>
    <strong>Racewhite:</strong>
    <%= demographic.raceWhite %>
  </p>
  <p>
    <strong>Racedidnotprovide:</strong>
    <%= demographic.raceDidNotProvide %>
  </p>
  <p>
    <strong>Gender:</strong>
    <%= demographic.gender %>
  </p>
  <p>
    <strong>Dateofbirth:</strong>
    <%= demographic.dateOfBirth %>
  </p>
  <p>
    <strong>Cityofbirth:</strong>
    <%= demographic.cityOfBirth %>
  </p>
  <p>
    <strong>Stateofbirth:</strong>
    <%= demographic.stateOfBirth %>
  </p>
  <p>
    <strong>Language:</strong>
    <%= demographic.language %>
  </p>
  <p>
    <strong>Military:</strong>
    <%= demographic.military %>
  </p>
  <p>
    <strong>Parent1educationallevel:</strong>
    <%= demographic.parent1EducationalLevel %>
  </p>
  <p>
    <strong>Parent2educationallevel:</strong>
    <%= demographic.parent2EducationalLevel %>
  </p>
  <p>
    <strong>Currenthouseholdincome:</strong>
    <%= demographic.currentHouseholdIncome %>
  </p>
  <%= link_to "Edit this demographic information", edit_leader_demographic_path(@leader, demographic) %>
</div>

app/views/demographics/_form.html.erb
<%= form_with(model: [@leader, demographic]) do |form| %>
  <% if demographic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(demographic.errors.count, "error") %> prohibited this demographic from being saved:</h2>
      <ul>
        <% demographic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :leader_id, style: "display: block" %>
    <%= form.text_field :leader_id %>
  </div>
  <div>
    <%= form.label :raceAmericanIndian, style: "display: block" %>
    <%= form.checkbox :raceAmericanIndian %>
  </div>
  <div>
    <%= form.label :raceAsian, style: "display: block" %>
    <%= form.checkbox :raceAsian %>
  </div>
  <div>
    <%= form.label :raceBlack, style: "display: block" %>
    <%= form.checkbox :raceBlack %>
  </div>
  <div>
    <%= form.label :raceHispanic, style: "display: block" %>
    <%= form.checkbox :raceHispanic %>
  </div>
  <div>
    <%= form.label :raceHawaiian, style: "display: block" %>
    <%= form.checkbox :raceHawaiian %>
  </div>
  <div>
    <%= form.label :raceWhite, style: "display: block" %>
    <%= form.checkbox :raceWhite %>
  </div>
  <div>
    <%= form.label :raceDidNotProvide, style: "display: block" %>
    <%= form.checkbox :raceDidNotProvide %>
  </div>
  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>
  <div>
    <%= form.label :dateOfBirth, style: "display: block" %>
    <%= form.datetime_field :dateOfBirth %>
  </div>
  <div>
    <%= form.label :cityOfBirth, style: "display: block" %>
    <%= form.text_field :cityOfBirth %>
  </div>
  <div>
    <%= form.label :stateOfBirth, style: "display: block" %>
    <%= form.text_field :stateOfBirth %>
  </div>
  <div>
    <%= form.label :language, style: "display: block" %>
    <%= form.text_field :language %>
  </div>
  <div>
    <%= form.label :military, style: "display: block" %>
    <%= form.text_field :military %>
  </div>
  <div>
    <%= form.label :parent1EducationalLevel, style: "display: block" %>
    <%= form.text_field :parent1EducationalLevel %>
  </div>
  <div>
    <%= form.label :parent2EducationalLevel, style: "display: block" %>
    <%= form.text_field :parent2EducationalLevel %>
  </div>
  <div>
    <%= form.label :currentHouseholdIncome, style: "display: block" %>
    <%= form.text_field :currentHouseholdIncome %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/demographics/edit.html.erb
<% content_for :title, "Editing demographic information" %>
<h1>Editing demographic information</h1>
<%= render "form", demographic: @demographic %>
<br>
<div>
  <%= link_to "Back to demographic information", leader_demographics_path %>
</div>

app/views/demographics/index.html.erb
<p style="color: green"><%= notice %></p>
<% content_for :title, "Demographic information" %>
<h1>Demographic information</h1>
<div class="columns">
  <div class="column">
    <%= render "application/sidebar", leader:@leader %>
  </div>
  <div class="column is-three-quarters">
    <%= render @demographic %>
  </div>
</div>