config/routes.rb
Rails.application.routes.draw do
  resources :leaders do
    resources :contact_informations
    resources :emergency_contacts
    resources :demographics
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "leaders#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_sidebar.html.erb
<ul>
  <li>
    <%= link_to "Name", leader_path(leader.id) %>
  </li>
  <li>
    <%= link_to "Contact Information", leader_contact_informations_path(leader.id) %>
  </li>
  <li>
    <%= link_to "Emergency Contact", leader_emergency_contacts_path(leader.id) %>
  </li>
  <li>
    <%= link_to "Demographic Information", leader_demographics_path(leader.id) %>
  </li>
</ul>